nbdkit 1.38: Fix inclusion of <gnutls/socket.h> with old gnutls
Development branch commit 8ce65bac5a ("build: Move to minimum gnutls
>= 3.5.18") changed the way that <gnutls/socket.h> is included.  I
didn't cherry pick this commit to the stable-1.38 branch since we
don't want to force people to update gnutls.

However when I cherry picked commit 47987e43bd ("server/crypto.c:
Check <gnutls/socket.h> works before including it"), I missed that
there was still a place where <gnutls/socket.h> was included (which
would have been fixed by the commit above).

The upshot is that compilation of nbdkit 1.38.3 fails on mingw:

In file included from ../../server/crypto.c:69:
/usr/i686-w64-mingw32/sys-root/mingw/include/gnutls/socket.h:32:10: fatal error: sys/socket.h: No such file or directory
   32 | #include <sys/socket.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

Fixes: commit f889d822dd96bcf8c0427bd541d730d58b166d83