rust: Fix "overindented" list in comment
  error: doc list item overindented
     --> src/lib.rs:934:9
      |
  934 |     ///             and/or [`Flags::FUA`].
      |         ^^^^^^^^^^^^ help: try using `  ` (2 spaces)
      |
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items
      = note: `-D clippy::doc-overindented-list-items` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(clippy::doc_overindented_list_items)]`

(cherry picked from commit d4a909f70f52db1c437a92d689b70ff93496399a)