sparse: Avoid PAGE_SIZE naming conflict
POSIX says <limits.h> on an XSI system must define PAGESIZE and
PAGE_SIZE as aliases to one another.  This triggered an Alpine Linux
build failure:

sparse.c:112: error: "PAGE_SIZE" redefined [-Werror]
  112 | #define PAGE_SIZE 32768
      |
In file included from /usr/include/fortify/stdlib.h:30,
                 from sparse.c:36:
/usr/include/limits.h:97: note: this is the location of the previous definition
   97 | #define PAGE_SIZE PAGESIZE
      |

The obvious fix is to rename our usage to avoid the names reserved by
POSIX (since we really want our pages to be a fixed size, even if the
platform offers a different native page size).

Signed-off-by: Eric Blake <eblake@redhat.com>
(cherry picked from commit c5be8885fd7686a754954aedfe96077f1ee58919)
Signed-off-by: Eric Blake <eblake@redhat.com>