rust: Use c_char instead of signed type for aarch64
On aarch64 we get the error below, because char is unsigned on that
platform.

error[E0308]: mismatched types
    --> examples/ramdisk.rs:72:9
     |
72   |         debug!("connection opened: readonly={}, tls={}", _readonly, tls);
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |         |
     |         expected `u8`, found `i8`
     |         arguments to this function are incorrect
     |
     = note: expected raw pointer `*const u8`
                found raw pointer `*const i8`
note: function defined here
    --> /home/rjones/d/nbdkit/plugins/rust/src/lib.rs:1069:12
     |
1069 |     pub fn nbdkit_debug(fmt: *const c_char, ...);
     |            ^^^^^^^^^^^^
     = note: this error originates in the macro `debug` (in Nightly builds, run with -Z macro-backtrace for more info)