rust: Declare explicit extern "C" API
Lots of errors like this:

  error: extern declarations without an explicit ABI are deprecated
     --> src/lib.rs:314:16
      |
  314 |     pub(super) extern fn after_fork() -> c_int {
      |                ^^^^^^ help: explicitly specify the C ABI: `extern "C"`
      |
      = note: `-D missing-abi` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(missing_abi)]`

(cherry picked from commit dcf15bf46ae30dbb17a05e40efddd25db65fca62)