tests: Fix CI on Fedora 40
Fedora 40 recently changed to move malloc debugging out of glibc into
glibc-utils (https://issues.redhat.com/browse/RHEL-35971).  Reflect
that in our CI, to avoid spurious test failures from tons of messages
like:

ERROR: ld.so: object 'libc_malloc_debug.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

by regenerating with libvirt-ci@fc5cedfb8
https://gitlab.com/libvirt/libvirt-ci/-/merge_requests/491

Also, change configure.ac to gracefully skip malloc debugging when
glibc-utils is not installed.

Signed-off-by: Eric Blake <eblake@redhat.com>
(cherry picked from commit 83cb0dc31ae44059212a28c4e6005f2b83823169)