server: Initialize error variables to NULL
On RHEL 8 we get this compile warning / error:

public.c: In function ‘nbdkit_parse_size’:
public.c:352:5: error: ‘pstr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     nbdkit_error ("%s: %s", error, pstr);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
public.c:352:5: error: ‘error’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

This is not in fact possible, and newer GCC can follow the
code across modules to prove it, but older GCC does not.  Path
of least resistance is to initialize the variables.

Updates: commit 29ce734ad5a94f371187000ac42d24f840eb5d97