time-limit: Replace ESHUTDOWN error on Windows
Windows does not have ESHUTDOWN:

time-limit.c: In function 'check_time_limit':
time-limit.c:130:14: error: 'ESHUTDOWN' undeclared (first use in this function); did you mean 'ENETDOWN'?
  130 |       *err = ESHUTDOWN;
      |              ^~~~~~~~~
      |              ENETDOWN

Fixes: commit 80fe8411755c907ca8a1ff2336f73801a7d0e8c9