bzip2: Fix mingw build
On Windows, <bzlib.h> sucks in <windows.h>; this namespace pollution
is gross, and breaks our builds if that public header is included
before <nbdkit-filter.h> which must pull in winsock.

                 from bzip2.c:49:
/usr/i686-w64-mingw32/sys-root/mingw/include/winsock2.h:15:2: error: #warning Please include winsock2.h before windows.h [-Werror=cpp]

Signed-off-by: Eric Blake <eblake@redhat.com>