server/crypto.c: Fix fallback functions used when gnutls is unavailable
The return value was wrong resulting in these errors:

crypto.c: In function ‘nbdkit_peer_tls_dn’:
crypto.c:945:3: error: return makes pointer from integer without a cast [-Werror]
   return -1;
   ^
crypto.c: In function ‘nbdkit_peer_tls_issuer_dn’:
crypto.c:953:3: error: return makes pointer from integer without a cast [-Werror]
   return -1;
   ^

Fixes: commit a3759199c93300cf9de24a129c4141609dacb047
Fixes: commit bf77f76112e3ffbc9149a54fbeb0a505310f28a2