qcow2dec: Fix fallback paths when zlib/zstd is not present
Need to use { ... } around this code since they begin with a variable
declaration.

qcow2dec.c: In function 'read_compressed_cluster':
qcow2dec.c:836:5: error: a label can only be part of a statement and a declaration is not a statement
     static _Atomic int zstd_show_error = 1;
     ^

Fixes: commit f333faa41dcdfa5d4747fcab3013f93167add4d1