file: Fix do_fallocate debugging on Alpine
Alpine has some weird/old kernel that doesn't support
FALLOC_FL_ZERO_RANGE but does support FALLOC_FL_PUNCH_HOLE, so the
debugging I added in commit ecf6b15fa8 failed to compile with:

  file.c: In function 'do_fallocate':
  file.c:958:27: error: 'FALLOC_FL_ZERO_RANGE' undeclared (first use in this function)
    958 |                   mode_ & FALLOC_FL_ZERO_RANGE ? " FALLOC_FL_ZERO_RANGE" : "",
        |                           ^~~~~~~~~~~~~~~~~~~~
  file.c:958:27: note: each undeclared identifier is reported only once for each function it appears in
  make[3]: *** [Makefile:666: nbdkit_file_plugin_la-file.lo] Error 1

Fixes: commit ecf6b15fa84a02b74ea969f06552c82ee418b9b4