rust: Add const {} around thread_local initializers
error: initializer for `thread_local` value can be made `const`
  --> tests/common/mod.rs:39:52
   |
39 | thread_local!(pub static ERRMSG: RefCell<String> = RefCell::new(String::new()));
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `const { RefCell::new(String::new()) }`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#thread_local_initializer_can_be_made_const
   = note: `-D clippy::thread-local-initializer-can-be-made-const` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::thread_local_initializer_can_be_made_const)]`
error: initializer for `thread_local` value can be made `const`
  --> tests/common/mod.rs:40:48
   |
40 | thread_local!(pub static ERRNO: RefCell<i32> = RefCell::new(0));
   |                                                ^^^^^^^^^^^^^^^ help: replace with: `const { RefCell::new(0) }`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#thread_local_initializer_can_be_made_const

Fixes: https://gitlab.com/nbdkit/nbdkit/-/jobs/6217464950
(cherry picked from commit 5179336084449aa3e0d01a5c8839f9d775c6be0e)