build: Default USDT probes to off on FreeBSD and macOS
It fails on FreeBSD with:

ld: error: undefined symbol: __dtrace_nbdkit___handle_single_connection
>>> referenced by connections.c:151
>>>               nbdkit-connections.o:(handle_single_connection)
ld: error: undefined symbol: __dtrace_nbdkit___preconnect
>>> referenced by plugins.c:295
>>>               nbdkit-plugins.o:(plugin_preconnect)
cc: error: linker command failed with exit code 1 (use -v to see invocation)

I believe we have to run a special 'dtrace -G' command here to
generate an object file that we have to link in, unlike on Linux.

On macOS the failure is a bit different:

connections.c:151:3: error: call to undeclared function 'DTRACE_PROBE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  151 |   DTRACE_PROBE (nbdkit, handle_single_connection);
      |   ^
connections.c:151:17: error: use of undeclared identifier 'nbdkit'
  151 |   DTRACE_PROBE (nbdkit, handle_single_connection);
      |                 ^
2 errors generated.

Fixes: commit 17824c20dd674ec8435e2292f2e8ba677f2b409f