rust: Fix clippy uninlined-format-args warning
warning: the MSRV in `clippy.toml` and `Cargo.toml` differ; using `1.63.0` from `clippy.toml`
error: variables can be used directly in the `format!` string
   --> src/lib.rs:305:18
    |
305 |             x => panic!("Undocumented return value {} from nbdkit_add_extent", x)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
    = note: `-D clippy::uninlined-format-args` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::uninlined_format_args)]`
help: change this to
    |
305 -             x => panic!("Undocumented return value {} from nbdkit_add_extent", x)
305 +             x => panic!("Undocumented return value {x} from nbdkit_add_extent")
    |
warning: `nbdkit` (lib) generated 1 warning

(cherry picked from commit 5e0e9e7b750f1ead40838437c062328cd91b8aaf)