stats: Remove bogus adjustment of freed pointer
The code freed a pointer and then (apparently in error) added a number
to the pointer.  Although simply adding to but never using such a
pointer wouldn't usually cause a problem, it contravenes the spec, and
GCC warns about it.  Since the adjustment is unused, remove it.

stats.cpp: In function 'void print_histogram(const nbdstat*)':
stats.cpp:266:16: error: pointer 'total_size' may be used after 'void free(void*)' [-Werror=use-after-free]
  266 |     total_size += st->size.at(bits);
      |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
stats.cpp:264:9: note: call to 'void free(void*)' here
  264 |     free(total_size);
      |     ~~~~^~~~~~~~~~~~

Fixes: commit 9f0226e3c29952578d70da614b49fde6114eb8e7